### ISSUE TITLE
About the go-github-release-test

### ISSUE THREAD

**Issue by suntong** [solvingJ/go-github-release-test#2]
Hi @solvingj, 

Does the go-github-release-test has anything to do with Go programs? 

I'm following your advice from https://github.com/goreleaser/goreleaser/issues/242#issuecomment-307843088 and am trying Bintray now, which led me to your this test repo. 

If I have a Go project, would this go-github-release-test be of any help for me to create Debian repo? 

Thanks

**Comment by solvingj** [comment]
Yes, the original library it is designed to help you with that exactly.  It turns out that there's very little in the utilities which are specific or proprietary to go, so I'm using it to package C++ projects and it works just as well. 

Please note that the Author has thus far demonstrated little intention to maintain any of the projects.  he was responding to github issues for a week or two, then stopped across the board (it's been about a month of silence).  Meanwhile, the authors github activity shows him forking and creating many other new libraries. 

This is quite unfortunate, as I feel this set was quite prolific, and appeared on github in a very mature and well-formed state.  They are only slightly less-than-perfect at this time, but very usable in my opinion.  I've accepted that I'll have to maintain my own forks if i intended to use them long-term.

Also, in my opinion, the author went 1 step too far in the abstraction for his examples and CI recipes.  I strongly suggestion you avoid lines like this: 
`- curl -L https://raw.githubusercontent.com/mh-cbon/go-bin-deb/master/create-pkg.sh
    | GH=mh-cbon/$MYAPP sh -`

It's fairly clear he did this because he set everything up to use github releases because he was unaware of Bintray. When I get back around to publishing some upcoming packages, I'll be modifying his tutorials to demonstrate the use of bintray, and skipping the massive complications around setting up repositories on github.io, and his "latest-version" scripting. 


I just wanted to be sure to share my compliments on the libraries involved, along with a disclaimer about the support factor.

**Comment by suntong** [comment]
Thanks for the comprehensive reply. I totally agree on every bit, especially those to avoid. 

Alright then, I'll be looking forward to your updated tutorials (and trying out Bintray from the command line meanwhile).

**Comment by solvingj** [comment]
You bet, hope it works out.  Yes, the JFrog CLI smoothed over a bunch of little nuisances with CI and testing things locally across platforms.  Cross-platform binary CLI tools really are still particularly valuable.  I also owe the JFrog CLI team some time.

**Comment by suntong** [comment]
Hi @solvingj, Just FYI that I'm satisfied with the Go building and uploading solution that I newly found now --

- https://github.com/suntong/hello-world-go
- https://github.com/suntong/travis-bintray-test

I meant, feel free to close it any way you want.
